### ISSUE TITLE
selenium driver.quit() 시 OSError 발생하는 것에 대한 컨트롤 추가

### ISSUE THREAD

**Issue by jms7446** [jms7446/etc#16]
아래와 같은 상황에 대한 try 추가
Traceback (most recent call last):
  File "sb_crawl.py", line 83, in <module>
    run_crawl(option.conf, option.scraper, option.jobs, option.messenger_name)
  File "sb_crawl.py", line 73, in run_crawl
    scraper.online_crawl()
  File "/home/msjung/project/etc/src/crawl/Scraper.py", line 51, in online_crawl
    self.login_driver.close()
  File "/home/msjung/project/etc/src/crawl/Scraper.py", line 84, in close
    self._driver.quit()
  File "/home/msjung/anaconda2/lib/python2.7/site-packages/selenium/webdriver/phantomjs/webdriver.py", line 76, in quit
    self.service.stop()
  File "/home/msjung/anaconda2/lib/python2.7/site-packages/selenium/webdriver/common/service.py", line 149, in stop
    self.send_remote_shutdown_command()
  File "/home/msjung/anaconda2/lib/python2.7/site-packages/selenium/webdriver/phantomjs/service.py", line 67, in send_remote_shutdown_command
    os.close(self._cookie_temp_file_handle)
OSError: [Errno 9] Bad file descriptor
Exception OSError: OSError(9, 'Bad file descriptor') in <bound method LoginDriver.__del__ of <crawl.Scraper.LoginDriver object at 0x7f0c8b4f0890>> ignored

**Comment by jms7446** [comment]
이 에러가 생겼을 때, phantomjs 가 정상적으로 닫히지 않은 것이 관찰됨. 
https://stackoverflow.com/questions/25110624/how-to-properly-stop-phantomjs-execution
에 있는 강제로 프로세스를 죽이는 것이 필요할 수도 있음.
